<?php
/**
 * @file
 * Defines all the hooks this module implements.
 */

/**
 * Implements hook menu()
 */
function agile_harris_matrix_menu() {
  $items['agile/harris'] = array(
    'title' => 'Show Visualizations',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'get_all_matrix_nodes',
    'file' => 'includes/utilities.inc',
    'access arguments' => array('access content'),
  );
  $items['agile/matrix'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => 'show_matrix_visualization',
    'file' => 'includes/utilities.inc',
    'access arguments' => array('access content'),
  );
  $items['agile/term_callback'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => 'agile_harris_matrix_get_term',
    'file' => 'includes/utilities.inc',
    'access arguments' => array('access content'),
  );
  $items['admin/config/system/d3_config'] = array(
    'description' => 'Configure Harris Matrix D3.',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer site configuration'),
    'page arguments' => array('agile_harris_matrix_admin_form'),
    'file' => 'includes/admin.form.inc',
    'title' => 'Configure D3 Visualizations',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function agile_harris_matrix_theme($existing, $type, $theme, $path) {
  return array(
    'agile_harris_matrix' => array(
      'template' => 'theme/harris_matrix',
      'file' => 'theme/theme.inc',
      'variables' => array('nid' => NULL),
    ),
  );
}

/**
 * Implements hook_form_alter().
 */
function agile_harris_matrix_form_harris_matrix_node_form_alter(&$form, &$form_state, $form_id) {
  $form['field_json']['#type'] = 'hidden';
}

